apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-test
spec:
  dnsNames:
  - "litmus.k8s.remi-ziolkowski.fr"
  issuerRef:
    name: letsencrypt
  secretName: "litmus-k8s-remi-ziolkowski-fr"
