apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: {{ .Values.groupName | quote }}
          solverName: ovh
          config:
            endpoint: ovh-eu
            applicationKey: {{ .Values.applicationKey | quote }}
            applicationSecretRef:
              key: applicationSecret
              name: ovh-credentials
            consumerKey: {{ .Values.consumerKey | quote }}
